### ISSUE TITLE
Ordernar consulta do pedido 

### ISSUE THREAD

**Issue by eberson** [fiap-postech/tech-challenge#52]
A lista de pedidos deverá retornar os pedidos com suas descrições, ordenados por recebimento e por status com a seguinte prioridade: Pronto > Em Preparação > Recebido; Pedidos com status Finalizado não devem aparecer na lista.

**Comment by antoniogabrielti** [comment]
A ordenação desse item então com base nesse enunciado ficou:

1- DELIVERED ("Entregue")
2- MADE (Pronto)
3- MAKING (Em Preparação)
4- PAID (Recebido)
